### ISSUE TITLE
hubot pager schedule myschedule fails

### ISSUE THREAD

**Issue by ingardm** [hubot-scripts/hubot-pager-me#67] opened 2015-11-17 09:47 UTC
The following error appears on the console:
[Tue Nov 17 2015 10:44:16 GMT+0100 (CET)] ERROR TypeError: undefined is not a function
  at SlackBot.send (/home/ingard/src/chatops/hubot/node_modules/hubot-slack/src/slack.coffee:217:47, <js>:265:19)
  at Response.send (/home/ingard/src/chatops/hubot/node_modules/hubot/src/response.coffee:22:5, <js>:20:47)
  at /home/ingard/src/chatops/hubot/node_modules/hubot-pager-me/src/scripts/pagerduty.coffee:696:9, <js>:786:17
  at /home/ingard/src/chatops/hubot/node_modules/hubot-pager-me/src/scripts/pagerduty.coffee:689:7, <js>:775:16
  at /home/ingard/src/chatops/hubot/node_modules/hubot-pager-me/src/pagerduty.coffee:138:7, <js>:185:16
  at /home/ingard/src/chatops/hubot/node_modules/hubot-pager-me/src/pagerduty.coffee:46:9, <js>:76:16
  at IncomingMessage.<anonymous> (/home/ingard/src/chatops/hubot/node_modules/hubot-pager-me/node_modules/scoped-http-client/src/index.js:95:22)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)

**Comment by stephenyeargin** [comment] 2015-11-17 14:46
Just to help debug, can you check which version of the package your Hubot is using? We have released several patches in the last few days.

**Comment by ingardm** [comment] 2015-11-17 17:40
hubot-pager-me@2.1.9 node_modules/hubot-pager-me

**Comment by stephenyeargin** [comment] 2015-11-17 17:46
Cool, that's the latest, so the bug must be in `master`. And was this your call to the bot?

`User> hubot pager schedules`

I know that @TheFynx and @mmrobins have been working with that particular call (and some related bugs), so I'm CC'ing them on this one.

**Comment by mmrobins** [comment] 2015-11-17 23:13
argh, took me awhile to reproduce since at first I was just testing with `/.bin/hubot`, but hit it quickly once I finally tried to upgrade my hubot to 2.1.9.  It's because I left some debug output in that doesn't blow things up in console, but does in at least the slack adapter.

**Comment by ingardm** [comment] 2015-11-18 12:53
@stephenyeargin yes I did hubot: pager schedule mysched

**Comment by ingardm** [comment] 2015-11-18 12:59
I can confirm the fix mentioned by @mmrobins works for me also

**Comment by stephenyeargin** [comment] 2015-11-18 20:12
Fixed in `v2.1.10`

**Closed** 2015-11-18 20:11 UTC
